'use client';

import { useState } from 'react';
import { mockApi } from '@/lib/api';
import { CodeSnippet } from '../components/CodeSnippet';

interface MockUser {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  age: number;
  image: string;
  company: string;
  phone: string;
  address: {
    city: string;
    state: string;
    country: string;
  };
}

export function CaseMocking() {
  const [users, setUsers] = useState<MockUser[]>([]);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);

    const res = await mockApi.get<MockUser>('/users/random');

    if (res.ok) {
      setUsers((prev) => [res.value, ...prev].slice(0, 8));
    }
    setLoading(false);
  };

  const handleClear = () => setUsers([]);

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-white">
          Case 3 — Dynamic Mocking{' '}
          <span className="text-white/30 font-normal text-lg">(Faker.js)</span>
        </h2>
        <p className="mt-2 text-white/40 max-w-2xl">
          The Mock plugin intercepts requests to{' '}
          <code className="text-indigo-400">/users/random</code> and returns data
          generated by <strong className="text-amber-400">Faker.js</strong> factory functions.
          No network request is made — all data is generated locally.
        </p>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-4">
        <button onClick={handleGenerate} disabled={loading} className="btn-glow text-white disabled:opacity-50">
          {loading ? (
            <span className="flex items-center gap-2">
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/20 border-t-white" />
              Generating…
            </span>
          ) : (
            '🎭 Generate Random User'
          )}
        </button>
        {users.length > 0 && (
          <button onClick={handleClear} className="btn-outline">
            Clear All
          </button>
        )}
        <span className="badge-info">{users.length} generated</span>
      </div>

      {/* Generated users */}
      {users.length > 0 && (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {users.map((user, i) => (
            <div
              key={`${user.id}-${i}`}
              className="glass-card-hover p-5 animate-slide-up"
              style={{ animationDelay: `${i * 50}ms` }}
            >
              <div className="flex items-center gap-3 mb-4">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={user.image}
                  alt={`${user.firstName} avatar`}
                  className="h-10 w-10 rounded-full ring-2 ring-indigo-500/30"
                />
                <div className="min-w-0">
                  <p className="text-sm font-semibold text-white truncate">
                    {user.firstName} {user.lastName}
                  </p>
                  <p className="text-xs text-white/30 truncate">{user.email}</p>
                </div>
              </div>

              <div className="space-y-1.5 text-xs text-white/40">
                <div className="flex justify-between">
                  <span>Age</span>
                  <span className="text-white/60">{user.age}</span>
                </div>
                <div className="flex justify-between">
                  <span>Company</span>
                  <span className="text-white/60 truncate ml-4">{user.company}</span>
                </div>
                <div className="flex justify-between">
                  <span>City</span>
                  <span className="text-white/60 truncate ml-4">{user.address.city}</span>
                </div>
                <div className="flex justify-between">
                  <span>Country</span>
                  <span className="text-white/60 truncate ml-4">{user.address.country}</span>
                </div>
              </div>

              <div className="mt-3 pt-3 border-t border-white/[0.04]">
                <span className="badge-warning text-[10px]">ID: {user.id}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Code */}
      <CodeSnippet
        title="Mock Plugin Setup"
        code={`import { createAxioRes } from 'axio-res';
import { faker } from '@faker-js/faker';

const api = createAxioRes({
  baseURL: 'https://dummyjson.com',
  plugins: {
    mock: {
      enabled: true,
      delay: 600,  // Simulate network latency
      dataMap: {
        '/users/random': () => ({
          // Factory function — called on every request
          id: faker.number.int({ min: 1, max: 9999 }),
          firstName: faker.person.firstName(),
          lastName: faker.person.lastName(),
          email: faker.internet.email(),
          age: faker.number.int({ min: 18, max: 80 }),
          image: faker.image.avatar(),
          company: faker.company.name(),
        }),
      },
    },
  },
});

// Each call returns different data:
const user1 = await api.get('/users/random'); // → "Alice Smith"
const user2 = await api.get('/users/random'); // → "Bob Jones"`}
      />
    </div>
  );
}
